//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.14 at 08:08:58 PM CEST 
//


package paper4all.nachrichten;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "messageOrMsgGroup",
    "trailer"
})
@XmlRootElement(name = "Interchange")
public class Interchange {

    @XmlAttribute(name = "standard_key", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String standardKey;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlElement(name = "Header")
    protected Header header;
    @XmlElements({
        @XmlElement(name = "Message", type = Message.class),
        @XmlElement(name = "MsgGroup", type = MsgGroup.class)
    })
    protected List<Object> messageOrMsgGroup;
    @XmlElement(name = "Trailer")
    protected Trailer trailer;

    /**
     * Gets the value of the standardKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardKey() {
        return standardKey;
    }

    /**
     * Sets the value of the standardKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardKey(String value) {
        this.standardKey = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the messageOrMsgGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageOrMsgGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageOrMsgGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * {@link MsgGroup }
     * 
     * 
     */
    public List<Object> getMessageOrMsgGroup() {
        if (messageOrMsgGroup == null) {
            messageOrMsgGroup = new ArrayList<Object>();
        }
        return this.messageOrMsgGroup;
    }

    /**
     * Gets the value of the trailer property.
     * 
     * @return
     *     possible object is
     *     {@link Trailer }
     *     
     */
    public Trailer getTrailer() {
        return trailer;
    }

    /**
     * Sets the value of the trailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trailer }
     *     
     */
    public void setTrailer(Trailer value) {
        this.trailer = value;
    }

}
