
package paper4all.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LagerService", targetNamespace = "http://webservices.paper4all/", wsdlLocation = "http://localhost:8080/lager?wsdl")
public class LagerService
    extends Service
{

    private final static URL LAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(paper4all.webservices.LagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = paper4all.webservices.LagerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/lager?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/lager?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LAGERSERVICE_WSDL_LOCATION = url;
    }

    public LagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LagerService() {
        super(LAGERSERVICE_WSDL_LOCATION, new QName("http://webservices.paper4all/", "LagerService"));
    }

    /**
     * 
     * @return
     *     returns LagerWebService
     */
    @WebEndpoint(name = "LagerWebServicePort")
    public LagerWebService getLagerWebServicePort() {
        return super.getPort(new QName("http://webservices.paper4all/", "LagerWebServicePort"), LagerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LagerWebService
     */
    @WebEndpoint(name = "LagerWebServicePort")
    public LagerWebService getLagerWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.paper4all/", "LagerWebServicePort"), LagerWebService.class, features);
    }

}
