
package paper4all.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LagerWebService", targetNamespace = "http://webservices.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LagerWebService {


    /**
     * 
     * @param second
     * @param first
     * @return
     *     returns double
     */
    @WebMethod(operationName = "add-two-numbers")
    @WebResult(name = "add-result", targetNamespace = "")
    @RequestWrapper(localName = "add-two-numbers", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.AddTwoNumbers")
    @ResponseWrapper(localName = "add-two-numbersResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.AddTwoNumbersResponse")
    public double addTwoNumbers(
        @WebParam(name = "first", targetNamespace = "")
        double first,
        @WebParam(name = "second", targetNamespace = "")
        double second);

    /**
     * 
     * @return
     *     returns java.util.List<paper4all.webservices.Sended>
     */
    @WebMethod(operationName = "sended-products")
    @WebResult(name = "sended-result", targetNamespace = "")
    @RequestWrapper(localName = "sended-products", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.SendedProducts")
    @ResponseWrapper(localName = "sended-productsResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.SendedProductsResponse")
    public List<Sended> sendedProducts();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloLager", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.HelloLager")
    @ResponseWrapper(localName = "helloLagerResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.HelloLagerResponse")
    public String helloLager();

}
