
package paper4all.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EDIToXMLService", targetNamespace = "http://services.paper4all/", wsdlLocation = "http://localhost:8080/editoxml?wsdl")
public class EDIToXMLService
    extends Service
{

    private final static URL EDITOXMLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/editoxml?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        EDITOXMLSERVICE_WSDL_LOCATION = url;
    }

    public EDIToXMLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDIToXMLService() {
        super(EDITOXMLSERVICE_WSDL_LOCATION, new QName("http://services.paper4all/", "EDIToXMLService"));
    }

    /**
     * 
     * @return
     *     returns EDIToXMLWebService
     */
    @WebEndpoint(name = "EDIToXMLWebServicePort")
    public EDIToXMLWebService getEDIToXMLWebServicePort() {
        return (EDIToXMLWebService)super.getPort(new QName("http://services.paper4all/", "EDIToXMLWebServicePort"), EDIToXMLWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EDIToXMLWebService
     */
    @WebEndpoint(name = "EDIToXMLWebServicePort")
    public EDIToXMLWebService getEDIToXMLWebServicePort(WebServiceFeature... features) {
        return (EDIToXMLWebService)super.getPort(new QName("http://services.paper4all/", "EDIToXMLWebServicePort"), EDIToXMLWebService.class, features);
    }

}
