
package paper4all.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderProcessorWebService", targetNamespace = "http://services.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessorWebService {


    /**
     * 
     * @param xmlOrderContent
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "process-incoming-order")
    @WebResult(name = "success-result", targetNamespace = "")
    @RequestWrapper(localName = "process-incoming-order", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.ProcessIncomingOrder")
    @ResponseWrapper(localName = "process-incoming-orderResponse", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.ProcessIncomingOrderResponse")
    public boolean processIncomingOrder(
        @WebParam(name = "xmlOrderContent", targetNamespace = "")
        String xmlOrderContent);

}
