
package paper4all.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderProcessorService", targetNamespace = "http://services.paper4all/", wsdlLocation = "http://localhost:8080/orderprocessor?wsdl")
public class OrderProcessorService
    extends Service
{

    private final static URL ORDERPROCESSORSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/orderprocessor?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ORDERPROCESSORSERVICE_WSDL_LOCATION = url;
    }

    public OrderProcessorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessorService() {
        super(ORDERPROCESSORSERVICE_WSDL_LOCATION, new QName("http://services.paper4all/", "OrderProcessorService"));
    }

    /**
     * 
     * @return
     *     returns OrderProcessorWebService
     */
    @WebEndpoint(name = "OrderProcessorWebServicePort")
    public OrderProcessorWebService getOrderProcessorWebServicePort() {
        return (OrderProcessorWebService)super.getPort(new QName("http://services.paper4all/", "OrderProcessorWebServicePort"), OrderProcessorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessorWebService
     */
    @WebEndpoint(name = "OrderProcessorWebServicePort")
    public OrderProcessorWebService getOrderProcessorWebServicePort(WebServiceFeature... features) {
        return (OrderProcessorWebService)super.getPort(new QName("http://services.paper4all/", "OrderProcessorWebServicePort"), OrderProcessorWebService.class, features);
    }

}
