
package paper4all.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReadInboxWebService", targetNamespace = "http://services.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReadInboxWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "read-from-inbox")
    @WebResult(name = "filename-result", targetNamespace = "")
    @RequestWrapper(localName = "read-from-inbox", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.ReadFromInbox")
    @ResponseWrapper(localName = "read-from-inboxResponse", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.ReadFromInboxResponse")
    public String readFromInbox();

}
