
package paper4all.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "XMLToEDIService", targetNamespace = "http://services.paper4all/", wsdlLocation = "http://localhost:8080/xmltoedi?wsdl")
public class XMLToEDIService
    extends Service
{

    private final static URL XMLTOEDISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/xmltoedi?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        XMLTOEDISERVICE_WSDL_LOCATION = url;
    }

    public XMLToEDIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XMLToEDIService() {
        super(XMLTOEDISERVICE_WSDL_LOCATION, new QName("http://services.paper4all/", "XMLToEDIService"));
    }

    /**
     * 
     * @return
     *     returns XMLToEDIWebService
     */
    @WebEndpoint(name = "XMLToEDIWebServicePort")
    public XMLToEDIWebService getXMLToEDIWebServicePort() {
        return (XMLToEDIWebService)super.getPort(new QName("http://services.paper4all/", "XMLToEDIWebServicePort"), XMLToEDIWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XMLToEDIWebService
     */
    @WebEndpoint(name = "XMLToEDIWebServicePort")
    public XMLToEDIWebService getXMLToEDIWebServicePort(WebServiceFeature... features) {
        return (XMLToEDIWebService)super.getPort(new QName("http://services.paper4all/", "XMLToEDIWebServicePort"), XMLToEDIWebService.class, features);
    }

}
