
package paper4all.WHinterface;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StorageService", targetNamespace = "http://service.server.endlessStorage/", wsdlLocation = "file:/C:/Users/darie/Desktop/data%20Types/WSDL_Storage/storage.wsdl")
public class StorageService
    extends Service
{

    private final static URL STORAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(paper4all.WHinterface.StorageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = paper4all.WHinterface.StorageService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/darie/Desktop/data%20Types/WSDL_Storage/storage.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/darie/Desktop/data%20Types/WSDL_Storage/storage.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STORAGESERVICE_WSDL_LOCATION = url;
    }

    public StorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageService() {
        super(STORAGESERVICE_WSDL_LOCATION, new QName("http://service.server.endlessStorage/", "StorageService"));
    }

    /**
     * 
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StoragePort")
    public Storage getStoragePort() {
        return super.getPort(new QName("http://service.server.endlessStorage/", "StoragePort"), Storage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StoragePort")
    public Storage getStoragePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.endlessStorage/", "StoragePort"), Storage.class, features);
    }

}
