
package paper4all.WHinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StorageService", targetNamespace = "http://service.server.endlessStorage/", wsdlLocation = "http://10.18.76.114:8089/storage?wsdl")
public class StorageService
    extends Service
{

    private final static URL STORAGESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://10.18.76.114:8089/storage?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STORAGESERVICE_WSDL_LOCATION = url;
    }

    public StorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageService() {
        super(STORAGESERVICE_WSDL_LOCATION, new QName("http://service.server.endlessStorage/", "StorageService"));
    }

    /**
     * 
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StoragePort")
    public Storage getStoragePort() {
        return (Storage)super.getPort(new QName("http://service.server.endlessStorage/", "StoragePort"), Storage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StoragePort")
    public Storage getStoragePort(WebServiceFeature... features) {
        return (Storage)super.getPort(new QName("http://service.server.endlessStorage/", "StoragePort"), Storage.class, features);
    }

}
