
package paper4all.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DeleteFileService", targetNamespace = "http://services.paper4all/", wsdlLocation = "http://localhost:8080/deletefile?wsdl")
public class DeleteFileService
    extends Service
{

    private final static URL DELETEFILESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/deletefile?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        DELETEFILESERVICE_WSDL_LOCATION = url;
    }

    public DeleteFileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteFileService() {
        super(DELETEFILESERVICE_WSDL_LOCATION, new QName("http://services.paper4all/", "DeleteFileService"));
    }

    /**
     * 
     * @return
     *     returns DeleteFileWebService
     */
    @WebEndpoint(name = "DeleteFileWebServicePort")
    public DeleteFileWebService getDeleteFileWebServicePort() {
        return (DeleteFileWebService)super.getPort(new QName("http://services.paper4all/", "DeleteFileWebServicePort"), DeleteFileWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteFileWebService
     */
    @WebEndpoint(name = "DeleteFileWebServicePort")
    public DeleteFileWebService getDeleteFileWebServicePort(WebServiceFeature... features) {
        return (DeleteFileWebService)super.getPort(new QName("http://services.paper4all/", "DeleteFileWebServicePort"), DeleteFileWebService.class, features);
    }

}
