
package paper4all.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EDIToXMLWebService", targetNamespace = "http://services.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EDIToXMLWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "edi-to-xml")
    @WebResult(name = "filenameXML-result", targetNamespace = "")
    @RequestWrapper(localName = "edi-to-xml", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.EdiToXml")
    @ResponseWrapper(localName = "edi-to-xmlResponse", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.EdiToXmlResponse")
    public String ediToXml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
