
package paper4all.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WriteOutboxService", targetNamespace = "http://services.paper4all/", wsdlLocation = "http://localhost:8080/writeoutbox?wsdl")
public class WriteOutboxService
    extends Service
{

    private final static URL WRITEOUTBOXSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/writeoutbox?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WRITEOUTBOXSERVICE_WSDL_LOCATION = url;
    }

    public WriteOutboxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WriteOutboxService() {
        super(WRITEOUTBOXSERVICE_WSDL_LOCATION, new QName("http://services.paper4all/", "WriteOutboxService"));
    }

    /**
     * 
     * @return
     *     returns WriteOutboxWebService
     */
    @WebEndpoint(name = "WriteOutboxWebServicePort")
    public WriteOutboxWebService getWriteOutboxWebServicePort() {
        return (WriteOutboxWebService)super.getPort(new QName("http://services.paper4all/", "WriteOutboxWebServicePort"), WriteOutboxWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WriteOutboxWebService
     */
    @WebEndpoint(name = "WriteOutboxWebServicePort")
    public WriteOutboxWebService getWriteOutboxWebServicePort(WebServiceFeature... features) {
        return (WriteOutboxWebService)super.getPort(new QName("http://services.paper4all/", "WriteOutboxWebServicePort"), WriteOutboxWebService.class, features);
    }

}
