
package paper4all.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "XMLToEDIWebService", targetNamespace = "http://services.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XMLToEDIWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "xml-to-edi")
    @WebResult(name = "filenameEDI-result", targetNamespace = "")
    @RequestWrapper(localName = "xml-to-edi", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.XmlToEdi")
    @ResponseWrapper(localName = "xml-to-ediResponse", targetNamespace = "http://services.paper4all/", className = "paper4all.wsdl.XmlToEdiResponse")
    public String xmlToEdi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
