//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.30 at 11:52:49 AM CEST 
//


package paper4all.rubyParser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rubyParser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rubyParser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link DE }
     * 
     */
    public DE createDE() {
        return new DE();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link MsgGroup }
     * 
     */
    public MsgGroup createMsgGroup() {
        return new MsgGroup();
    }

    /**
     * Create an instance of {@link CDE }
     * 
     */
    public CDE createCDE() {
        return new CDE();
    }

    /**
     * Create an instance of {@link SegmentGroup }
     * 
     */
    public SegmentGroup createSegmentGroup() {
        return new SegmentGroup();
    }

    /**
     * Create an instance of {@link Interchange }
     * 
     */
    public Interchange createInterchange() {
        return new Interchange();
    }

    /**
     * Create an instance of {@link Trailer }
     * 
     */
    public Trailer createTrailer() {
        return new Trailer();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

}
