
package paper4all.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BuchhaltungWebService", targetNamespace = "http://webservices.paper4all/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BuchhaltungWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloBuchhaltung", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.HelloBuchhaltung")
    @ResponseWrapper(localName = "helloBuchhaltungResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.HelloBuchhaltungResponse")
    public String helloBuchhaltung();

    /**
     * 
     * @param second
     * @param first
     * @return
     *     returns double
     */
    @WebMethod(operationName = "multiply-two-numbers")
    @WebResult(name = "multiply-result", targetNamespace = "")
    @RequestWrapper(localName = "multiply-two-numbers", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.MultiplyTwoNumbers")
    @ResponseWrapper(localName = "multiply-two-numbersResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.MultiplyTwoNumbersResponse")
    public double multiplyTwoNumbers(
        @WebParam(name = "first", targetNamespace = "")
        double first,
        @WebParam(name = "second", targetNamespace = "")
        double second);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "receive-a-string")
    @WebResult(name = "fileName-result", targetNamespace = "")
    @RequestWrapper(localName = "receive-a-string", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.ReceiveAString")
    @ResponseWrapper(localName = "receive-a-stringResponse", targetNamespace = "http://webservices.paper4all/", className = "paper4all.webservices.ReceiveAStringResponse")
    public String receiveAString(
        @WebParam(name = "content", targetNamespace = "")
        String content);

}
