
package paper4all.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BuchhaltungService", targetNamespace = "http://webservices.paper4all/", wsdlLocation = "http://localhost:8080/buchhaltung?wsdl")
public class BuchhaltungService
    extends Service
{

    private final static URL BUCHHALTUNGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/buchhaltung?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BUCHHALTUNGSERVICE_WSDL_LOCATION = url;
    }

    public BuchhaltungService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuchhaltungService() {
        super(BUCHHALTUNGSERVICE_WSDL_LOCATION, new QName("http://webservices.paper4all/", "BuchhaltungService"));
    }

    /**
     * 
     * @return
     *     returns BuchhaltungWebService
     */
    @WebEndpoint(name = "BuchhaltungWebServicePort")
    public BuchhaltungWebService getBuchhaltungWebServicePort() {
        return (BuchhaltungWebService)super.getPort(new QName("http://webservices.paper4all/", "BuchhaltungWebServicePort"), BuchhaltungWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuchhaltungWebService
     */
    @WebEndpoint(name = "BuchhaltungWebServicePort")
    public BuchhaltungWebService getBuchhaltungWebServicePort(WebServiceFeature... features) {
        return (BuchhaltungWebService)super.getPort(new QName("http://webservices.paper4all/", "BuchhaltungWebServicePort"), BuchhaltungWebService.class, features);
    }

}
