
package paper4all.WHinterface;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Storage", targetNamespace = "http://service.server.endlessStorage/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Storage {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "sendOrderToStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.SendOrderToStorage")
    public void sendOrderToStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns paper4all.WHinterface.Inventory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInventoryFromStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.GetInventoryFromStorage")
    @ResponseWrapper(localName = "getInventoryFromStorageResponse", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.GetInventoryFromStorageResponse")
    public Inventory getInventoryFromStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "sendReservationToStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.SendReservationToStorage")
    public void sendReservationToStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "pickUpReservationFromStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.PickUpReservationFromStorage")
    public void pickUpReservationFromStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservationPickup arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns paper4all.WHinterface.SgtinWhereAbouts
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSGTINWhereaboutsFromStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.GetSGTINWhereaboutsFromStorage")
    @ResponseWrapper(localName = "getSGTINWhereaboutsFromStorageResponse", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.GetSGTINWhereaboutsFromStorageResponse")
    public SgtinWhereAbouts getSGTINWhereaboutsFromStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "sendSaledProductsToStorage", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.SendSaledProductsToStorage")
    public void sendSaledProductsToStorage(
        @WebParam(name = "arg0", targetNamespace = "")
        SaledProducts arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "arrivals", targetNamespace = "http://service.server.endlessStorage/", className = "paper4all.WHinterface.Arrivals")
    public void arrivals(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

}
